### ISSUE TITLE
Artist name for ringtone/notification set as a numeric value

### ISSUE THREAD

**Issue by PaulNealeGit** [Hiraqui/cordova-plugin-ringtone#2]
On my device, the artist name is being set as '2130968576', but looking at the code it seems like it should be the app name?  Would it be possible to add artist name as a parameter for the JS 'exportAssetAndSetRingtone' function so it could be set dynamically in the same way as the ringtone title? Related to this is the fact that the line 'import com.hiraqui.myApplication.R' in Ringtone.java can't be changed when using PhoneGap Build - for testing I've had to set my app ID to 'com.hiraqui.myApplication' - and it seems like that line is only needed for getting the app name to use as the artist name?  So if you were able to remove that line, and get the artist name via another method as I mentioned, this plugin would also be compatible with PhoneGap Build.

**Comment by Hiraqui** [comment]
Hello again Paul, new parameter added to both functions, the string "artist". if the parameter equals null or it's an empty string "", the artist would be the App name by default. Removed de R asset dependency. Try it out.
