### ISSUE TITLE
Good Plugin - Current Status

### ISSUE THREAD

**Issue by philecom** [Hiraqui/cordova-plugin-ringtone#4]
I think this is a brilliant plugin. 
I will like to know if it is still being maintain and any future plan of adding support for iOS and Windows

**Comment by Hiraqui** [comment]
At the moment I am not maintaining it to be honest, haven't fully tried it in Android 6 actually but I think it works fine. In iOS it's not possible to override the ringtones from an application for now (OS decision), that's why there's no ringtone plugin.
