### ISSUE TITLE
 Permissions sdk > 22 / Android 6.0

### ISSUE THREAD

**Issue by klingelkasten** [Hiraqui/cordova-plugin-ringtone#6]
Dear Hiraqui,

thank you the plugin is working fine!

But I dont get it to work with sdk > 22.  I cant request for WRITE_SETTINGS with neither 
cordova-plugin-android-permissions 
plugin, nor
cordova.plugins.diagnostic 

Can you go more into details how to do it or give an example?

Thanks in advance!

Henry

**Comment by hypesol** [comment]
same issue with me. please guide us. thanks

**Comment by Hiraqui** [comment]
#5 Hi guys, this is explained in this issue
